#! /bin/bash

GUARD=_VIRTNET_BACKEND_GLUE_GEN_H

backends=""
for objfile in "$@"; do
	backends="$backends $(echo $objfile | sed "s/virtnet_\(.*\).o/\1/")"
done
echo $backends 1>&2

cat << END_CAT
/* file generated by $(basename $0). do not edit */
#ifndef $GUARD
#define $GUARD

#ifndef _VIRTNET_H
#error do not include directly. use "virtnet.h"
#endif
struct virtnet_backend_ops;
END_CAT

echo "/* backends */"
for backend in $backends; do
	echo "extern struct virtnet_backend_ops VIRTNET_BACKEND($backend);"
done
echo

cat << END_CAT
/* glue */
#define VIRTNET_BACKEND_GLUE() \\
END_CAT

for backend in $backends; do
	echo -e "\tVIRTNET_BACKEND_ENTRY($backend) \\"
done
echo

cat << END_CAT

#endif /* $GUARD */
END_CAT
