#! /bin/bash

GUARD=_VIRTNET_BACKEND_GLUE_GEN_H

backends=""
for objfile in "$@"; do
	backends="$backends $(echo $objfile | sed "s/virtnet_\(.*\).o/\1/")"
done
echo $backends 1>&2

cat << END_CAT
/* file generated by $(basename $0). do not edit */
#ifndef $GUARD
#define $GUARD

END_CAT

cat << END_CAT
#define VIRTNET_BACKEND_GLUE() \\
END_CAT

for backend in $backends; do
	echo -e "\tVIRTNET_BACKEND_ENTRY($backend) \\"
done
echo

cat << END_CAT

#endif /* $GUARD */
END_CAT
